# Initial configuration file for doing experiments with Biophysical network
notes: "Test"
general:
  record: True
  record_rate: # TODO: record every x ms
  simtime: # ms
  seed: 0
neuron:
  types:
    exc:
    inh:
  params:
    ATP_H_mean:
    ATP_H_ds:
    ATP_I_mean:
    ATP_I_ds:
    ATP_H_dist:
    ATP_I_dist:
    # TODO: include distributions for:
    # g_leak
    # capacitance
    # tau_m
    # tau_syn (both)
    # tau_refrac
    #
connection:
  types:
    exc_exc:
      conn_spec:
      syn_spec:
        # TODO
        # model: stdp_synapse
        # tau_minus
        # tau_plus
        # alpha
        # weight # exponential distribution
        # delay # uniform distribution
    exc_inh:
    inh_inh:
    inh_exc:
  params:
    max_weight:
    min_weight:
    stdp_decay: # for ATP dependent weights
    weight_masc:
    homeostatic_plasticity: False
network_layout:
  energy_dependent: True
  weights_distribution:
  neurons_distribution:
  delays_distribution:
  n_neurons: 100
  exc_inh_ratio: 0.8 # n_exc = exc_inh_ratio*n_neurons
external_source:
  noise_type:
  target_neurons_id:
