# Initial configuration file for doing experiments with Biophysical network
notes: "Test"
general:
  record: True
  record_rate: 1 # TODO: record every x ms
  simtime: 100 # ms
  seed: 0
neurons:
  ex:
    model: "iaf_psc_alpha"
    params:
      energy_params:
        # Initial condition for ATP
        ATP:
          mean: 100
          std: 0
        # ATP production parameter
        K_ATP:
          mean: 1
          std: 0
        # action-potential energy consumption time-constant
        tau_ap:
          mean: 30
          std: 0
        # Time constant of synaptic consumption
        tau_syn_atp_in:
          mean: 20
          std: 0
        tau_syn_atp_ex:
          mean: 20
          std: 0
        # resting-potential consumption percent/ms
        E_rp:
          mean: 5  # %
          std: 0
        # housekeeping consumption percent/ms
        E_hk:
          mean: 5  # %
          std: 0
        # action potential consumption percent/spike
        E_ap:
          mean: 15  # %
          std: 0
        #synaptic consumption percent/spike
        E_syn_ex:
          mean: 8  # %
          std: 0
        E_syn_in:
          mean: 5  # %
          std: 0
        # sensitivity to energy imbalance
        gamma:
          mean: 16
          std: 0
      general_params:
        # synaptic time constants
        tau_syn_ex:
          mean: 6
          std: 1
        tau_syn_in:
          mean: 6
          std: 1
        # membrane time constant
        tau_m:
          mean: 2
          std: 0.1
        # capacitance
        C_m:
          mean: 250
          std: 12
        # refractory period
        t_ref:
          mean: 2
          std: 0.1
  in:
    model: "iaf_psc_alpha"
    params:
      energy_params:
        # Initial condition for ATP
        ATP:
          mean: 100
          std: 0
        # ATP production parameter
        K_ATP:
          mean: 1
          std: 0
        # action-potential energy consumption time-constant
        tau_ap:
          mean: 30
          std: 0
        # Time constant of synaptic consumption
        tau_syn_atp_in:
          mean: 20
          std: 0
        tau_syn_atp_ex:
          mean: 20
          std: 0
        # resting-potential consumption percent/ms
        E_rp:
          mean: 5  # %
          std: 0
        # housekeeping consumption percent/ms
        E_hk:
          mean: 5  # %
          std: 0
        # action potential consumption percent/spike
        E_ap:
          mean: 15  # %
          std: 0
        #synaptic consumption percent/spike
        E_syn_ex:
          mean: 8  # %
          std: 0
        E_syn_in:
          mean: 5  # %
          std: 0
        # sensitivity to energy imbalance
        gamma:
          mean: 16
          std: 0
      general_params:
        # synaptic time constants
        tau_syn_ex:
          mean: 6
          std: 1
        tau_syn_in:
          mean: 6
          std: 1
        # membrane time constant
        tau_m:
          mean: 2
          std: 0.1
        # capacitance
        C_m:
          mean: 250
          std: 12
        # refractory period
        t_ref:
          mean: 2
          std: 0.1
#  connecting populations
connections:
  ex_ex:
    # connection parameters
    conn_spec:
      allow_autapses: True # bool
      allow_multapses: True # bool
      rule: "pairwise_bernoulli"
      p:  # TODO gaussian kernel centered in each neuron
    # synaptic parameters
    syn_spec:
      synapse_model: "stdp_synapse"
      weights_dist: "exponential" # exponential, normal or uniform
      delays_dist: "uniform" # exponential, normal or uniform
      alphas_dist: "uniform"
      # TODO
      # model: stdp_synapse
      # tau_minus
      # tau_plus
      # alpha
      # weight # exponential distribution
      # delay # uniform distribution
  ex_in: ""
  in_in: ""
  in_ex: ""
  params:
    # TODO separe this for each connection type
    max_weight:
    min_weight:
    stdp_decay: # for ATP dependent weights
    weight_mask:
    homeostatic_plasticity: False
network_layout:
  energy_dependent: True
  n_neurons: 5
  ex_in_ratio: 0.8 # n_exc = exc_inh_ratio*n_neurons
  weights_distribution: "exponential" # "exponential" or "normal"
  weights_dist_beta: 1
  weights_dist_mean: 10
  weights_dist_sd: 3
  delays_distribution: "uniform"
  positions:
    dist: "uniform"
    dim: 2 # number of spatial dimensions (2 or 3)
    pos_bounds:
      # TODO include real values
      - -1
      - 1
external_source:
  noise_type:
  target_neurons_id:
